rabbitmq.host=localhost
rabbitmq.port=5672
rabbitmq.username=guest
rabbitmq.password=guest
rabbitmq.vhost=/zavabank
rabbitmq.events.exchange=zava.events
rabbitmq.ingestion.routingKey=file.ingested

db.url=jdbc:sqlserver://sqlserver:1433;databaseName=ZavaBankCore;encrypt=false;trustServerCertificate=true
db.username=sa
db.password=YourStrong!Passw0rd

ingestion.watch.path=/shared/file-ingestion
ingestion.processed.path=/shared/file-ingestion/processed
ingestion.error.path=/shared/file-ingestion/error
ingestion.poll.interval.ms=5000
