servicebus.namespace=
servicebus.topic.name=zava.events
servicebus.ingestion.subject=file.ingested
servicebus.managedIdentityClientId=

db.url=jdbc:sqlserver://sqlserver:1433;databaseName=ZavaBankCore;encrypt=false;trustServerCertificate=true
db.username=sa
db.password=YourStrong!Passw0rd

ingestion.watch.path=/shared/file-ingestion
ingestion.processed.path=/shared/file-ingestion/processed
ingestion.error.path=/shared/file-ingestion/error
ingestion.poll.interval.ms=5000
